### PR TITLE
Fix TypeScript build failures (17 errors) and add CI

### PR DESCRIPTION
**Pull request by bcorner13**
## Summary

`npm run build` currently fails with **17 TypeScript errors**. They trace to **two root causes**, plus a third type error those were masking. This PR fixes all three and adds CI + guardrails so the build can't silently regress for future contributors.

This is the **build** half of a two-part split. The dependency/security fixes are in #6. The two are independent; see *Merge order* below.

## Root cause analysis

**1. Missing `@types/node` (16 of the 17 errors).**
The code imports Node built-ins (`http`, `child_process`, `url`, `path`, `fs`) and uses the `process` global and the `NodeJS` namespace, but `@types/node` was never added to `devDependencies`. With no Node type declarations available:
- every built-in import errored (`Cannot find module 'http' | 'fs' | 'url' | 'path' | 'child_process'`)
- `process` and `NodeJS` were undefined
- the HTTP handler's `req` / `res` fell back to implicit `any`

**2. Config key typo in `src/server/mcp.ts` (the 17th error).**
The config passed `toolMode: 'all'`, but `OpenAPIMCPServerConfig` from `@ivotoby/openapi-mcp-server` requires **`toolsMode`** (with an "s"). So `toolMode` was an unknown property and the required `toolsMode` was reported missing.

**3. Latent type error revealed once the above were fixed.**
`canonical_url` is `process.env.CONCRETE_CANONICAL_URL`, i.e. `string | undefined`, but `apiBaseUrl` requires `string`. This was hidden while the build was broken (the config object inferred as `any`). The module-level `if (!canonical_url ...) throw` guard does not narrow the exported `const`'s type — which is why `oidc.ts` had to use non-null assertions (`canonical_url!`, etc.).

## Changes

**Build fixes**
- Add `@types/node` to `devDependencies`.
- `src/server/mcp.ts`: `toolMode` → `toolsMode`; remove a now-dead `// @ts-ignore`.
- `src/env.ts`: a `requireEnv()` helper that throws on a missing variable and returns `string`. Exports are now typed `string`, preserving the original fail-fast behaviour with a clearer message.
- `src/auth/oidc.ts`: drop the 3 now-redundant `!` non-null assertions.

**Hardening for future users**
- **`.github/workflows/build.yml`** — runs `npm ci && npm run build` on Node 20/22/24 for every push and PR. Would have caught *both* primary failures.
- `package.json`: add `engines.node >= 20`, plus `typecheck` (`tsc --noEmit`) and `prepublishOnly` (`npm run build`) scripts.
- `tsconfig.json`: drop `scripts/**/*` from `include`. With `rootDir: "src"`, any file under a `scripts/` dir would break the build — a trap for the next contributor.

## Merge order

The lockfile in this PR is based on the post-`npm audit fix` state from #6, so **merging this in either order keeps the dependency tree secure** — this PR cannot revert #6's fixes. If #6 merges first, rebasing this branch reduces the lockfile delta to just the `@types/node` addition.

## Verification

```
npm ci && npm run build   # exit 0, emits dist/  (was: 17 errors)
npm run typecheck         # exit 0
npm audit                 # found 0 vulnerabilities
```

Verified on a clean `node_modules` install.

---
🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by bcorner13** [comment]
Cross-reference: #4 (by @mlocati) adds the `node:` prefix to the built-in imports, which is good practice and complementary — but on its own it doesn't make the build pass, since `node:http`/`node:fs`/etc. still need `@types/node` for their type declarations. This PR adds `@types/node`, fixes the `toolMode`→`toolsMode` config typo and the `apiBaseUrl` typing, and adds CI — the changes needed to actually get to a green `tsc`. The `node:` prefixes from #4 could be layered on top cleanly.

**Comment by bcorner13** [comment]
Thanks for merging mlocati's PRs! I've merged the latest `main` into this branch and updated `package-lock.json` as requested. A couple of things worth flagging:

### `@ivotoby/openapi-mcp-server` bumped 1.14.0 → 1.16.0 (within the declared `^1.12.1` range)

After merging main, a clean `npm ci && npm run build` started failing with:

```
src/server/mcp.ts(1,45): error TS7016: Could not find a declaration file for
module '@ivotoby/openapi-mcp-server'. '.../dist/bundle.js' implicitly has an 'any' type.
```

**Cause:** mlocati's lockfile regeneration (from March) pinned `@ivotoby/openapi-mcp-server` to **1.14.0**, whose published bundle ships **no type declarations** (`main: ./dist/bundle.js`, no `types` field). Version **1.16.0** added them (`types: ./dist/index.d.ts`). Both satisfy the declared `^1.12.1` range, and 1.16.0 is the current latest — so I ran `npm update @ivotoby/openapi-mcp-server` to bring the lockfile forward. This restores type resolution and is what makes the build green alongside the `@types/node` addition.

### Resolved the 8 npm audit vulnerabilities (6 moderate + 2 high → 0)

The merged tree inherited 8 advisories (axios, hono, fast-uri, follow-redirects, ip-address, qs, express-rate-limit, @hono/node-server). I applied `npm audit fix` — all remediations are within existing semver ranges, **no breaking changes**.

### Verification (clean, from scratch)

```
$ rm -rf node_modules dist && npm ci
added 127 packages, audited 128 packages
found 0 vulnerabilities

$ npm run build      # exit 0, dist/index.js emitted
$ npm run typecheck  # exit 0
```

Branch is now up to date with `main` and fully green. Happy to adjust if you'd prefer the `@ivotoby` bump split into its own commit/PR.

**Comment by hissy** [comment]
@bcorner13 

Thank you!
